import Head from 'next/head'
import Introduction from "../src/Components/Introduction";
import About from "../src/Components/About";
import Testimonial from "../src/Components/Testimonial";
import Contact from "../src/Components/Contact";
import Footer from "../src/Components/Footer";
import PickMeals from "../src/Assets/pick-meals-image.png";
import ChooseMeals from "../src/Assets/choose-image.png";
import DeliveryMeals from "../src/Assets/delivery-image.png";
import Image from "next/image";

export default function Home() {
  const workInfoData = [
    {
      image: PickMeals,
      title: "Escolher Refeições",
      text: "Lorem ipsum dolor sit amet consectetur. Maecenas orci et sagittis duis elementum interdum facilisi bibendum.",
    },
    {
      image: ChooseMeals,
      title: "Escolha com que frequência",
      text: "Lorem ipsum dolor sit amet consectetur. Maecenas orci et ",
    },
    {
      image: DeliveryMeals,
      title: "Entregas rápidas",
      text: "Lorem ipsum dolor sit amet consectetur. Maecenas orci et lorem ipsum",
    },
  ];
  return (
    <div>
      <Head>
        <title>template-laddingpage-4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"App"}>
        <Introduction/>
        <About/>
        <div className="work-section-wrapper" id={"trabalho"}>
          <div className="work-section-top">
            <p className="primary-subheading">Trabalho</p>
            <h1 className="primary-heading">Como funciona</h1>
            <p className="primary-text">
              Lorem ipsum dolor sit amet, consectetur. Não é um grande desenvolvedor, não é um desenvolvedor. Dolor turpis molestie dui large facilita um fringilla quam.
            </p>
          </div>
          <div className="work-section-bottom">
            {workInfoData.map((data) => (
              <div className="work-section-info" key={data.title}>
                <div className="info-boxes-img-container">
                  <Image src={data.image} alt="" width={141} height={141} />
                </div>
                <h2>{data.title}</h2>
                <p>{data.text}</p>
              </div>
            ))}
          </div>
        </div>
        <Testimonial/>
        <Contact/>
        <Footer/>
      </main>
    </div>
  )
}
